image: maven:latest

stages:
  - build
  - test

cache:
  paths:
    - /root/.m2/repository/

build:
  stage: build
  only:
    - GitlabTest
  script:
    - echo "BUILDING PROJECT"
    - mvn clean compile


test:
  stage: test
  only:
    - GitlabTest
  script:
    - echo "RUNNING TESTS"
    - mvn clean test -e
